# Generated by Django 3.2.4 on 2021-07-07 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodinward', '0002_prodinward_is_biiled'),
    ]

    operations = [
        migrations.AddField(
            model_name='prodinward',
            name='billed',
            field=models.IntegerField(default=0),
        ),
    ]
